input_files:
    tad_coordinates_hg18: 'data/tads_hESC_hg18.csv'
    raw_disgenet: 'data/curated_variant_disease_associations.tsv.gz'
    raw_gwascatalog: 'data/gwas_catalog_v1.0.2-associations_e92_r2018-06-20.tsv'
output_dirs:
    results: 'results'
    images: 'images'
filters:
    OR_threshold:  # <float>
    variant_type:  # 'nonexonic', 'intergenic'
