workdir: 'pipeline_run'

hic_sources:
    - GSE63525_IMR90

tool_paths:
    juicer_tools: 'hi-c/juicer_tools_1.13.02.jar'

input_files:
    raw_disgenet: 'data/curated_variant_disease_associations.tsv.gz'
    raw_gwascatalog: 'data/gwas_catalog_v1.0.2-associations_e94_r2018-09-30.tsv'
    disease_ontology: 'data/doid.owl'
    exp_factor_ontology: 'data/efo.owl'
    sequence_ontology: 'data/so.owl'

filters:
    OR_threshold:  # <float>
    variant_type_group:  # 'intergenic', 'intronic', 'exonic'

parameters:
    source_genomiccoordinates_version: hg38
    associated_gene_source: mapped  # 'reported', 'mapped'
    allow_snp_multiplicity_in_enrichment: false
