workdir: 'pipeline_run'

hic_sources:
    - GSE63525_IMR90

chromosome_list: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', 'X', 'Y']
window_size_list: [3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

snp_filters:
    nofilter: null
    exonic: 'variant_group == "exonic"'
    intronic: 'variant_group == "intronic"'
    intergenic: 'variant_group == "intergenic"'
    nonexonic: 'variant_group != "exonic"'

tool_paths:
    juicer_tools: 'hi-c/juicer_tools_1.13.02.jar'

input_files:
    disgenet: 'https://www.disgenet.org/static/disgenet_ap1/files/downloads/curated_variant_disease_associations.tsv.gz'
    gwascatalog: 'ftp://ftp.ebi.ac.uk/pub/databases/gwas/releases/latest/gwas-catalog-associations_ontology-annotated.tsv'
    exp_factor_ontology: 'http://www.ebi.ac.uk/efo/efo.owl'
    sequence_ontology: 'https://github.com/The-Sequence-Ontology/SO-Ontologies/raw/master/so.owl'

parameters:
    ensembl_url: 'grch37.ensembl.org'  # hg19/GRCh37/b37: 'grch37.ensembl.org', hg38/GRCh38: 'www.ensembl.org', <path to file>
    associated_gene_source: mapped  # 'reported', 'mapped'
    allow_snp_multiplicity_in_enrichment: false
