input_files:
    tad_coordinates: 'data/tads_hESC_hg18.csv'
    raw_disgenet: 'data/curated_variant_disease_associations.tsv.gz'
    raw_gwascatalog: 'data/gwas_catalog_v1.0.2-associations_e94_r2018-09-30.tsv'
output_dirs:
    results: 'results'
    images: 'images'
    cache: 'cache'
filters:
    OR_threshold:  # <float>
    variant_type:  # 'nonexonic', 'intergenic'
parameters:
    source_genomiccoordinates_version: hg18
    associated_gene_source: mapped  # 'reported', 'mapped'
    ppi_source: stringdb  # 'stringdb', 'biogrid'
    classification_tad_boundary_type: 20in  # '20in', '20out', '20inout', '40in', '40out', '40inout'
