workdir: 'pipeline_run'

hic_sources:
    - GSE63525_IMR90

chromosome_list: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', 'X', 'Y']
window_size_list: [3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

snp_filter_list:
    - 'nofilter'
    - 'variant_group=exonic'
    - 'variant_group=intronic'
    - 'variant_group=intergenic'

tool_paths:
    juicer_tools: 'hi-c/juicer_tools_1.13.02.jar'

input_files:
    raw_disgenet: 'data/curated_variant_disease_associations.tsv.gz'
    raw_gwascatalog: 'data/gwas_catalog_v1.0.2-associations_e94_r2018-09-30.tsv'
    disease_ontology: 'data/doid.owl'
    exp_factor_ontology: 'data/efo.owl'
    sequence_ontology: 'data/so.owl'

parameters:
    source_genomiccoordinates_version: hg19  # actually b37
    associated_gene_source: mapped  # 'reported', 'mapped'
    allow_snp_multiplicity_in_enrichment: false
