workdir: 'test_case/pipeline_test/'

hic_sources:
    - dummy

chromosome_list: ['chr1']
window_size_list: [42]

snp_filter_list:
    - 'nofilter'
    - 'variant_group=exonic'

tool_paths:
    juicer_tools: '../hi-c/juicer_tools_1.13.02.jar'

input_files:
    disgenet: 'test_case/data/disgenet_empty.tsv'
    gwascatalog: 'test_case/data/dummy_gwas_catalog.tsv'
    disease_ontology: 'test_case/data/dummy_doid.owl'
    exp_factor_ontology: 'test_case/data/dummy_efo.owl'
    sequence_ontology: 'test_case/data/dummy_so.owl'

parameters:
    ensembl_url: '../data/snp_annotations.csv'  # ".." because of workdir
    associated_gene_source: mapped  # 'reported', 'mapped'
    allow_snp_multiplicity_in_enrichment: false
